# Generated by Django 3.0.5 on 2020-04-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_lecture_lecture_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='l_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Lecture Name'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_date',
            field=models.DateTimeField(verbose_name='Lecture Start Date'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_date_end',
            field=models.DateTimeField(verbose_name='Lecture Finish Date'),
        ),
    ]
