# Generated by Django 3.0.5 on 2020-04-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0002_auto_20200417_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('image_events', models.FileField(blank=True, upload_to='image')),
                ('dept_name', models.ManyToManyField(to='department.Department')),
            ],
        ),
    ]
