# Generated by Django 3.0.5 on 2020-04-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Event Name'),
        ),
        migrations.AlterField(
            model_name='events',
            name='image_events',
            field=models.FileField(blank=True, upload_to='image', verbose_name='Picture of Event'),
        ),
    ]
