# Generated by Django 3.0.5 on 2020-04-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20200419_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ads_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Ad Name'),
        ),
    ]
