# Generated by Django 3.0.5 on 2020-04-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20200417_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='d_name',
            field=models.CharField(max_length=50, serialize=False, verbose_name='Department'),
        ),
    ]
