# Generated by Django 3.0.5 on 2020-04-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
                ('lecture_name', models.CharField(max_length=50)),
                ('classroom_name', models.CharField(max_length=50)),
            ],
        ),
    ]
