# Generated by Django 3.0.5 on 2020-04-16 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('lecture', '0001_initial'),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='department_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Department'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='lecture_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture'),
        ),
    ]
