# Generated by Django 3.0.5 on 2020-04-18 14:44

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20200416_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='field',
            field=models.TextField(default=django.utils.timezone.now, validators=[django.core.validators.URLValidator()]),
            preserve_default=False,
        ),
    ]
