# Generated by Django 3.0.5 on 2020-04-18 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_classroom_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='field',
        ),
    ]
